baseurl = "/"
title = "Eric Ngigi"
languageCode = "en-us"
paginate = "10" # Number of posts per page
theme = "mainroad"
disqusShortname = "" # Enable comments by entering your Disqus shortname
googleAnalytics = "" # Enable Google Analytics by entering your tracking id

[Params.author]
  name = "Eric Ngigi"
  bio = "Who Cares"
  avatar = "img/arch-02.png"

[Params]
  description = "Eric" # Description of your site
  copyright = "Eric Ngigi"
  opengraph = true
  schema = true
  twitter_cards = false
  readmore = false # Show "Read more" button in list if true
  authorbox = true
  pager = true
  post_meta = ["date", "categories"] # Order of post meta information
  mainSections = ["post", "docs"]
  googleFontsLink = "https://fonts.googleapis.com/css?family=Nunito+Sans:400,400i,700" # Load Google Fonts

[Params.logo]
  image = "img/cloud-image-1.png"
  title = "Eric Ngigi"
  subtitle = "Engineered for Efficiency: Cloud Automation Expertise" # Logo subtitle

[Params.sidebar]
  home = false   # Configure layout for home page
  list = false   # Configure layout for list pages
  single = false # Configure layout for single pages
  # Enable widgets in given order
  # widgets = ["search", "recent", "categories", "taglist"]
  widgets = ["categories", "taglist"]

# [Params.widgets]
#   recent_num = 5 # Set the number of articles in the "Recent articles" widget
#   tags_counter = false # Enable counter for each tag in "Tags" widget (disabled by default)

[Params.style.vars]
  highlightColor = "#E22D30"
  fontFamilyPrimary = "'Nunito Sans', Helvetica, Arial, sans-serif"
  fontFamilySecondary = "SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace"

[Author] # Used in authorbox
  name = "Eric Ngigi"
  bio = "Eric, a certified AWS Solution Architect, brings 4 years of expertise in cloud and DevOps technologies. Proficient in Linux administration, his mastery lies in Terraform for Infrastructure as Code (IaC) development, enabling scalable cloud deployments. Eric shares his insights and experiences through his blog, [EricNgigi](https://ericngigi.com)."
  avatar = "img/profile-picture.png"
